### ISSUE TITLE
Cover image for README.md

### ISSUE THREAD

**Issue by madalingorbanescu** [pixelgrade/bucket-lite#17]
@georgeolaru we will need you to help us with the cover image that will be added in README.md

**Comment by georgeolaru** [comment]
@madalingorbanescu Here you go: 

![github-bucket-lite](https://user-images.githubusercontent.com/1632775/61714481-9da95a80-ad63-11e9-905a-d4b52aa280f1.jpg)

I already add it to `readme.md`
